linters-settings:
  gocognit:
    min-complexity: 40

linters:
  enable-all: true
  disable:
    - lll
    - interfacer
    - gomnd
    - godox
    - dogsled
    - funlen
    - wsl
    - testpackage
    - exhaustivestruct
    - deadcode
    - golint
    - unparam
    - varcheck
  fast: false
